// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"layout/internal/migration"
	"layout/internal/repository"
)

import (
	_ "layout/pkg/config"
	_ "layout/pkg/redis"
)

// Injectors from wire.go:

func newApp() (*migration.Migrate, func(), error) {
	db := repository.NewDB()
	migrate := migration.NewMigrate(db)
	return migrate, func() {
	}, nil
}

// wire.go:

var RepositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewUserRepository)

var MigrateSet = wire.NewSet(migration.NewMigrate)
