// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireinject

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"layout/internal/handler"
	"layout/internal/repository"
	"layout/internal/router"
	"layout/internal/service"
)

// Injectors from wire.go:

func NewApp() (*gin.Engine, func(), error) {
	handlerHandler := handler.NewHandler()
	serviceService := service.NewService()
	db := repository.NewDB()
	repositoryRepository := repository.NewRepository(db)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	handlerRouter := &handler.Router{
		UserAPI: userHandler,
	}
	engine := router.NewServerHTTP(handlerRouter)
	return engine, func() {
	}, nil
}

// wire.go:

var ServerSet = wire.NewSet(router.NewServerHTTP, handler.StructProvider)
