// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"layout/internal/handler"
	"layout/internal/repository"
	"layout/internal/router"
	"layout/internal/service"
)

import (
	_ "layout/pkg/configParse"
	_ "layout/pkg/redis"
)

// Injectors from wire.go:

func newApp() (*gin.Engine, func(), error) {
	serviceService := service.NewService()
	db := repository.NewDB()
	repositoryRepository := repository.NewRepository(db)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(userService)
	engine := router.NewServerHTTP(userHandler)
	return engine, func() {
	}, nil
}

// wire.go:

var ServerSet = wire.NewSet(router.NewServerHTTP)

var HandlerSet = wire.NewSet(handler.NewUserHandler)

var ServiceSet = wire.NewSet(service.NewService, service.NewUserService)

var RepositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewUserRepository)
